services:
  oracle:
    # See the 'docker' subdirectory for the content of this image.
    # Note that we are using the sha256 hash of the image to ensure integrity.
    image: ghcr.io/oasisprotocol/demo-rofl:latest@sha256:7d7530a845eaa8038e50e43ef2aa192a4c7243b8d6102a2626eeea2c71eefb70
    platform: linux/amd64
    environment:
      # Address of the Echo contract deployed on Sapphire.
      # https://explorer.oasis.io/testnet/sapphire/address/0x5d683b980615A7A60B3cFf3DFC338A9985278fF3
      - CONTRACT_ADDRESS=0x5d683b980615A7A60B3cFf3DFC338A9985278fF3
      - MESSAGE=${MESSAGE}
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
