version: "3.8"

services:
  web:
    image: python:3.11-slim
    ports:
      - "5000:5000"
    command:
      - python
      - -c
      - |
        import os
        os.system('python -m pip install flask')


        from flask import Flask
        app = Flask(__name__)
        @app.route('/')
        def hello():
            return 'hello world'

        import httpx
        @app.route('/make-tx')
        async def makeTx():
            payload = {
              "tx": {
                "kind": "eth",
                "data": {
                    "gas_limit": 200000,
                    "to": CONTRACT_ADDRESS.removeprefix("0x"),
                    "value": 0,
                    "data": calldata.removeprefix("0x"),
                },
              },
              "encrypt": False,
            }
            async with httpx.AsyncClient(transport=httpx.AsyncHTTPTransport(uds="/run/rofl-appd.sock")) as client:
                response = await client.post(
                    full_url=http://localhost/rofl/v1/tx/sign-submit, json=payload
                )
                response.raise_for_status()
                return response.json()
            return 'submitted'

        if __name__ == '__main__':
            app.run(host='0.0.0.0', port=5000)
